image: docker:19.03.0

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.0-dind
stages:
  - test

test:
  stage: test
  tags:
    - training-test
  script:
    - docker network create testnetwork
    - docker build -t testserver .
    - docker run --name testserver -d -p 3000:3000 --network testnetwork testserver
    - sleep 3
    - docker run --rm -v $(pwd):/usr/src/app --network testnetwork hvphuong98/acexis-ft-test2
